		SELECT
	          DC.PARENT_SEC_CD PD
		, DF.WS_CD AS LINE
		, DM.SEC_NM LINE_NAME
		, DF.VEND_CD AS VEND_CD
		, MV.VEND_ANAME AS VEND_NAME
		, DF.ITEM_CD AS ITEM_CD
		, MI.ITEM_NAME ITEM_NAME
		, MP.MODEL 
--		, DF.DEFECT_FACTOR_CD  AS CD
		, SUM(DF.QTY) AS QTY
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '001' THEN DF.QTY END)) CD_001
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '002' THEN DF.QTY END)) CD_002
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '003' THEN DF.QTY END)) CD_003
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '004' THEN DF.QTY END)) CD_004
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '005' THEN DF.QTY END)) CD_005
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '006' THEN DF.QTY END)) CD_006
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '007' THEN DF.QTY END)) CD_007
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '008' THEN DF.QTY END)) CD_008
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '009' THEN DF.QTY END)) CD_009
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '010' THEN DF.QTY END)) CD_010
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '011' THEN DF.QTY END)) CD_011
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '012' THEN DF.QTY END)) CD_012
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '013' THEN DF.QTY END)) CD_013
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '100' THEN DF.QTY END)) CD_100
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '101' THEN DF.QTY END)) CD_101
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '102' THEN DF.QTY END)) CD_102
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '103' THEN DF.QTY END)) CD_103
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '104' THEN DF.QTY END)) CD_104
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '105' THEN DF.QTY END)) CD_105
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '106' THEN DF.QTY END)) CD_106
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '107' THEN DF.QTY END)) CD_107
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '108' THEN DF.QTY END)) CD_108
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '109' THEN DF.QTY END)) CD_109
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '110' THEN DF.QTY END)) CD_110
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '111' THEN DF.QTY END)) CD_111
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '112' THEN DF.QTY END)) CD_112
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '113' THEN DF.QTY END)) CD_113
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '114' THEN DF.QTY END)) CD_114
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '115' THEN DF.QTY END)) CD_115
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '117' THEN DF.QTY END)) CD_117
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '118' THEN DF.QTY END)) CD_118
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '119' THEN DF.QTY END)) CD_119
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '120' THEN DF.QTY END)) CD_120
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '121' THEN DF.QTY END)) CD_121
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '122' THEN DF.QTY END)) CD_122
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '123' THEN DF.QTY END)) CD_123
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '124' THEN DF.QTY END)) CD_124
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '125' THEN DF.QTY END)) CD_125
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '126' THEN DF.QTY END)) CD_126
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '127' THEN DF.QTY END)) CD_127
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '128' THEN DF.QTY END)) CD_128
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '129' THEN DF.QTY END)) CD_129
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '130' THEN DF.QTY END)) CD_130
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '131' THEN DF.QTY END)) CD_131
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '132' THEN DF.QTY END)) CD_132
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '133' THEN DF.QTY END)) CD_133
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '134' THEN DF.QTY END)) CD_134
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '135' THEN DF.QTY END)) CD_135
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '136' THEN DF.QTY END)) CD_136
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '137' THEN DF.QTY END)) CD_137
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '201' THEN DF.QTY END)) CD_201
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '202' THEN DF.QTY END)) CD_202
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '203' THEN DF.QTY END)) CD_203
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '204' THEN DF.QTY END)) CD_204
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '205' THEN DF.QTY END)) CD_205
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '206' THEN DF.QTY END)) CD_206
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '207' THEN DF.QTY END)) CD_207
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '208' THEN DF.QTY END)) CD_208
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '209' THEN DF.QTY END)) CD_209
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '210' THEN DF.QTY END)) CD_210
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '212' THEN DF.QTY END)) CD_212
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '213' THEN DF.QTY END)) CD_213
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '214' THEN DF.QTY END)) CD_214
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '215' THEN DF.QTY END)) CD_215
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '300' THEN DF.QTY END)) CD_300
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '301' THEN DF.QTY END)) CD_301
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '302' THEN DF.QTY END)) CD_302
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '303' THEN DF.QTY END)) CD_303
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '304' THEN DF.QTY END)) CD_304
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '305' THEN DF.QTY END)) CD_305
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '306' THEN DF.QTY END)) CD_306
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '307' THEN DF.QTY END)) CD_307
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '308' THEN DF.QTY END)) CD_308
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '309' THEN DF.QTY END)) CD_309
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '310' THEN DF.QTY END)) CD_310
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '311' THEN DF.QTY END)) CD_311
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '312' THEN DF.QTY END)) CD_312
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '313' THEN DF.QTY END)) CD_313
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '402' THEN DF.QTY END)) CD_401
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '403' THEN DF.QTY END)) CD_402
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '408' THEN DF.QTY END)) CD_403
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '412' THEN DF.QTY END)) CD_404
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '413' THEN DF.QTY END)) CD_405
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '414' THEN DF.QTY END)) CD_406
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '401' THEN DF.QTY END)) CD_407
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '404' THEN DF.QTY END)) CD_408
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '405' THEN DF.QTY END)) CD_409
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '406' THEN DF.QTY END)) CD_410
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '407' THEN DF.QTY END)) CD_411
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '409' THEN DF.QTY END)) CD_412
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '410' THEN DF.QTY END)) CD_413
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '411' THEN DF.QTY END)) CD_414
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '500' THEN DF.QTY END)) CD_500
		,ABS(SUM(CASE WHEN DF.DEFECT_FACTOR_CD = '501' THEN DF.QTY END)) CD_501
		,DF.ITEM_CD || MV.VEND_CD || DF.WS_CD  KEY_CK

		FROM
			UT_DEFECT_DISPOSAL DF
		, M_VEND_CTRL MV
		, M_PLANT_ITEM MP
		, M_ITEM MI
    		, VM_DEPARTMENT_CLASS DC 
		, VM_DEPARTMENT DM
		WHERE
		    DF.WS_CD = DC.COMP_SEC_CD(+)
		AND DF.WS_CD = DM.SEC_CD(+)
		AND DF.VEND_CD = MV.VEND_CD(+)
		AND DF.ITEM_CD = MI.ITEM_CD (+)
		AND DF.ITEM_CD = MP.ITEM_CD
		AND DF.PLANT_CD = MP.PLANT_CD(+)
		AND DF.DEL_FLG = 0
		--AND DF.ITEM_CD = '1132A102-RM'
		--AND DF.VEND_CD IS NULL
		--AND MP.MODEL IS NOT NULL
 		AND DF.RSLT_DATE >= TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,0),'MM'),'YYYY/MM/DD') AND DF.RSLT_DATE <= TO_CHAR(LAST_DAY(ADD_MONTHS(SYSDATE,0)),'YYYY/MM/DD')
		GROUP BY
		DF.VEND_CD
		, DF.WS_CD
		, DF.ITEM_CD
		, DC.PARENT_SEC_CD
		, MP.MODEL
		, MI.ITEM_NAME
		, MV.VEND_ANAME
		, DM.SEC_NM
		,DF.ITEM_CD || MV.VEND_CD || DF.WS_CD
	--	, DF.DEFECT_FACTOR_CD 
		ORDER BY 1,2