SELECT
 PD.PARENT_SEC_CD AS PD
,AD.VEND_CD AS VEND_CD
,MVC.VEND_ANAME
,AD.LINE AS LINE_CD
,VD.SEC_NM AS LINE_NAME
,MI.ITEM_CD AS ITEM_CD
,MI.ITEM_NAME AS ITEM_NAME
,MP.MODEL
--,TR.OPR_DATE AS PDATE
--,NVL(SUM(TR.ACPT_QTY),0) AS QTY

, (CASE WHEN AD.STATUS = 3 THEN AD.QTY END) RECEIVE
, (CASE WHEN AD.STATUS = 2 THEN AD.QTY END) ACUT
, ABS(CASE WHEN AD.STATUS = 1 THEN AD.QTY END) DEFT
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '001' THEN AD.QTY END) AS CD_001
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '002' THEN AD.QTY END) AS CD_002
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '003' THEN AD.QTY END) AS CD_003
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '004' THEN AD.QTY END) AS CD_004
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '005' THEN AD.QTY END) AS CD_005
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '006' THEN AD.QTY END) AS CD_006
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '007' THEN AD.QTY END) AS CD_007
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '008' THEN AD.QTY END) AS CD_008
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '009' THEN AD.QTY END) AS CD_009
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '010' THEN AD.QTY END) AS CD_010
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '011' THEN AD.QTY END) AS CD_011
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '012' THEN AD.QTY END) AS CD_012
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '013' THEN AD.QTY END) AS CD_013
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '100' THEN AD.QTY END) AS CD_100
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '101' THEN AD.QTY END) AS CD_101
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '102' THEN AD.QTY END) AS CD_102
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '103' THEN AD.QTY END) AS CD_103
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '104' THEN AD.QTY END) AS CD_104
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '105' THEN AD.QTY END) AS CD_105
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '106' THEN AD.QTY END) AS CD_106
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '107' THEN AD.QTY END) AS CD_107
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '108' THEN AD.QTY END) AS CD_108
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '109' THEN AD.QTY END) AS CD_109
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '110' THEN AD.QTY END) AS CD_110
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '111' THEN AD.QTY END) AS CD_111
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '112' THEN AD.QTY END) AS CD_112
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '113' THEN AD.QTY END) AS CD_113
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '114' THEN AD.QTY END) AS CD_114
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '115' THEN AD.QTY END) AS CD_115
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '117' THEN AD.QTY END) AS CD_117
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '118' THEN AD.QTY END) AS CD_118
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '119' THEN AD.QTY END) AS CD_119
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '120' THEN AD.QTY END) AS CD_120
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '121' THEN AD.QTY END) AS CD_121
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '122' THEN AD.QTY END) AS CD_122
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '123' THEN AD.QTY END) AS CD_123
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '124' THEN AD.QTY END) AS CD_124
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '125' THEN AD.QTY END) AS CD_125
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '126' THEN AD.QTY END) AS CD_126
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '127' THEN AD.QTY END) AS CD_127
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '128' THEN AD.QTY END) AS CD_128
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '129' THEN AD.QTY END) AS CD_129
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '130' THEN AD.QTY END) AS CD_130
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '131' THEN AD.QTY END) AS CD_131
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '132' THEN AD.QTY END) AS CD_132
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '133' THEN AD.QTY END) AS CD_133
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '134' THEN AD.QTY END) AS CD_134
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '135' THEN AD.QTY END) AS CD_135
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '136' THEN AD.QTY END) AS CD_136
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '137' THEN AD.QTY END) AS CD_137
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '201' THEN AD.QTY END) AS CD_201
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '202' THEN AD.QTY END) AS CD_202
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '203' THEN AD.QTY END) AS CD_203
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '204' THEN AD.QTY END) AS CD_204
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '205' THEN AD.QTY END) AS CD_205
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '206' THEN AD.QTY END) AS CD_206
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '207' THEN AD.QTY END) AS CD_207
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '208' THEN AD.QTY END) AS CD_208
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '209' THEN AD.QTY END) AS CD_209
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '210' THEN AD.QTY END) AS CD_210
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '212' THEN AD.QTY END) AS CD_212
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '213' THEN AD.QTY END) AS CD_213
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '214' THEN AD.QTY END) AS CD_214
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '215' THEN AD.QTY END) AS CD_215
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '300' THEN AD.QTY END) AS CD_300
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '301' THEN AD.QTY END) AS CD_301
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '302' THEN AD.QTY END) AS CD_302
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '303' THEN AD.QTY END) AS CD_303
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '304' THEN AD.QTY END) AS CD_304
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '305' THEN AD.QTY END) AS CD_305
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '306' THEN AD.QTY END) AS CD_306
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '307' THEN AD.QTY END) AS CD_307
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '308' THEN AD.QTY END) AS CD_308
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '309' THEN AD.QTY END) AS CD_309
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '310' THEN AD.QTY END) AS CD_310
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '311' THEN AD.QTY END) AS CD_311
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '312' THEN AD.QTY END) AS CD_312
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '313' THEN AD.QTY END) AS CD_313
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '314' THEN AD.QTY END) AS CD_314
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '315' THEN AD.QTY END) AS CD_315
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '316' THEN AD.QTY END) AS CD_316
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '317' THEN AD.QTY END) AS CD_317
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '318' THEN AD.QTY END) AS CD_318
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '319' THEN AD.QTY END) AS CD_319
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '401' THEN AD.QTY END) AS CD_401
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '402' THEN AD.QTY END) AS CD_402
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '403' THEN AD.QTY END) AS CD_403
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '404' THEN AD.QTY END) AS CD_404
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '405' THEN AD.QTY END) AS CD_405
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '406' THEN AD.QTY END) AS CD_406
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '407' THEN AD.QTY END) AS CD_407
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '408' THEN AD.QTY END) AS CD_408
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '409' THEN AD.QTY END) AS CD_409
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '410' THEN AD.QTY END) AS CD_410
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '411' THEN AD.QTY END) AS CD_411
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '412' THEN AD.QTY END) AS CD_412
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '413' THEN AD.QTY END) AS CD_413
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '414' THEN AD.QTY END) AS CD_414
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '415' THEN AD.QTY END) AS CD_415
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '416' THEN AD.QTY END) AS CD_416
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '500' THEN AD.QTY END) AS CD_500
, ABS(CASE WHEN AD.STATUS = 1 AND AD.CD = '501' THEN AD.QTY END) AS CD_501
, AD.ITEM_CD || AD.VEND_CD || AD.LINE  KEY_CK
FROM
 (
		SELECT
		  1 STATUS
		, DF.PLANT_CD
		, DF.VEND_CD AS VEND_CD
		, DF.WS_CD AS LINE
		, DF.ITEM_CD AS ITEM_CD
		, DF.DEFECT_FACTOR_CD  AS CD
		, SUM(DF.QTY) AS QTY
		FROM
	           UT_DEFECT_DISPOSAL DF
		WHERE
		   DF.DEL_FLG = 0
		--AND DF.VEND_CD IS NULL
 		AND TO_CHAR(DF.RSLT_DATE,'YYYY/MM/DD') >= TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,0),'MM'),'YYYY/MM/DD') AND TO_CHAR(DF.RSLT_DATE,'YYYY/MM/DD') <= TO_CHAR(SYSDATE-1,'YYYY/MM/DD')
		GROUP BY
			DF.VEND_CD
		,	DF.WS_CD
		, DF.ITEM_CD
		, DF.DEFECT_FACTOR_CD 
		, DF.PLANT_CD
		UNION ALL

		SELECT
	    2 STATUS
		, TR.PLANT_CD
		, NULL AS  VEND_CD
		, TR.WS_CD AS LINE
		, TR.ITEM_CD AS ITEM_CD
		, NULL AS CD 
		, SUM( TR.ACPT_QTY ) QTY
		FROM
		   T_OPR_RSLT TR
		WHERE
	          TO_CHAR(TR.OPR_DATE,'YYYY/MM/DD') >= TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,0),'MM'),'YYYY/MM/DD') AND TO_CHAR(TR.OPR_DATE,'YYYY/MM/DD') <= TO_CHAR(SYSDATE-1,'YYYY/MM/DD')
		AND TR.ACPT_QTY > 0
		GROUP BY
			TR.WS_CD
		, TR.ITEM_CD	
		, TR.PLANT_CD
		UNION ALL
		SELECT
			3 STATUS
		, PLANT_CD
		, VEND_CD AS VEND_CD
		, NULL    AS LINE
		, ITEM_CD AS ITEM_CD
		, NULL    AS CD
		, SUM(ACPT_QTY) AS QTY
		FROM
		  T_PAST_INSPC_ACPT
		WHERE 
		--TO_CHAR(ACPT_DATE,'YYYY/MM/DD') = TO_CHAR(SYSDATE-1,'YYYY/MM/DD')
		  TO_CHAR(ACPT_DATE,'YYYY/MM/DD') >= TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,0),'MM'),'YYYY/MM/DD') AND TO_CHAR(ACPT_DATE,'YYYY/MM/DD') <= TO_CHAR(SYSDATE-1,'YYYY/MM/DD')
		GROUP BY
		  VEND_CD
		, ITEM_CD
		, PLANT_CD
	 ) AD
,M_ITEM MI
,M_PLANT_ITEM MP
,VM_DEPARTMENT_CLASS PD 
,VM_DEPARTMENT VD
,M_VEND_CTRL MVC
WHERE
AD.ITEM_CD = MI.ITEM_CD(+)
AND AD.PLANT_Cd = MP.PLANT_CD
AND AD.ITEM_CD = MP.ITEM_CD(+)
AND AD.LINE = PD.COMP_SEC_CD(+)
AND AD.LINE = VD.SEC_CD(+)
AND AD.VEND_CD = MVC.VEND_CD(+)
AND ( PD.PARENT_SEC_CD != 'K1PL00' OR PD.PARENT_SEC_CD IS NULL )
--AND PD.PARENT_SEC_CD IS NOT NULL
AND MP.MODEL IS NOT NULL
--AND MI.ITEM_CD ='898228-3200-RM'
ORDER BY
	PD.PARENT_SEC_CD, AD.LINE, AD.ITEM_CD ASC