  SELECT 
      MB.COMP_TYP
    , MB.PARENT_ITEM_CD
    , MB.COMP_ITEM_CD
    , MB.ITEM_NAME
    , MB.COMP_MODEL
    , MB.USE_TOTAL
    , MB.UNIT
    , VC.PARENT_SEC_CD
    , VC.COMP_SEC_CD
    , MB.UPDATE_DATE
    --, MB.PRODUCT_TYP || '' || MB.PARENT_ITEM_CD || '#' || MB.MODEL || '#' || VC.PARENT_SEC_CD || '' || VC.COMP_SEC_CD KEY_UPDATE
	FROM 

	 (

  SELECT 
    MP.PARENT_ITEM_CD
  , MP.COMP_ITEM_CD
  , MI.ITEM_NAME
  , MM.MODEL COMP_MODEL
  , MM.PRODUCT_TYP COMP_TYP
  , MP.PS_UNIT_NUMERATOR USE_TOTAL
  ,CASE WHEN SUBSTR(MP.COMP_ITEM_CD, 1, 4) = 'T999' OR MP.COMP_ITEM_CD = 'ADC12' THEN 'Kg.' ELSE 'Pcs.' END UNIT
  --,MP.PARENT_ITEM_CD REF
  ,TO_CHAR(SYSDATE - 0.082, 'YYYY/MM/DD HH24:MI:SS') UPDATE_DATE

  FROM 
   M_PLANT_PS MP
  ,M_PLANT_ITEM MM 
  ,M_ITEM MI

  
  WHERE 
      MP.COMP_ITEM_CD = MM.ITEM_CD(+)
  AND MP.COMP_ITEM_CD = MI.ITEM_CD(+)
  AND MP.PARENT_ITEM_CD = '1060A196'

  ) MB
  ,M_SOURCE MS
  ,VM_DEPARTMENT_CLASS VC		
  WHERE 
   MB.PARENT_ITEM_CD = MS.ITEM_CD(+)
   AND MS.SOURCE_CD = VC.COMP_SEC_CD(+) 
   AND VC.PARENT_SEC_CD  IS NOT NULL
 --AND MB.PARENT_ITEM_CD = 'J100-11510'
  GROUP BY 		
      MB.COMP_TYP
    , MB.PARENT_ITEM_CD
    , MB.COMP_ITEM_CD
    , MB.ITEM_NAME
    , MB.COMP_MODEL
    , MB.USE_TOTAL
    , MB.UNIT
    , VC.PARENT_SEC_CD
    , VC.COMP_SEC_CD
    , MB.UPDATE_DATE
 ORDER BY 5


