SELECT
COUNT(BC.COMP_ITEM_CD) MC
FROM
(
  SELECT 
    MP.PARENT_ITEM_CD
  , MP.COMP_ITEM_CD
  , MI.ITEM_NAME
  , MM.MODEL COMP_MODEL
  , MM.PRODUCT_TYP COMP_TYP
  ,MP.PS_UNIT_NUMERATOR USE_TOTAL
  ,CASE WHEN SUBSTR(MP.COMP_ITEM_CD, 1, 4) = 'T999' OR MP.COMP_ITEM_CD = 'ADC12' THEN 'Kg.' ELSE 'Pcs.' END UNIT
  ,TO_CHAR(SYSDATE - 0.082, 'YYYY/MM/DD HH24:MI:SS') UPDATE_DATE

  FROM 
   M_PLANT_PS MP
  ,M_PLANT_ITEM MM 
  ,M_ITEM MI

  
  WHERE 
      MP.COMP_ITEM_CD = MM.ITEM_CD(+)
  AND MP.COMP_ITEM_CD = MI.ITEM_CD(+)
  AND MP.PARENT_ITEM_CD = 