		SELECT
     		  MV.VEND_NAME VEND_NAME
		, TA.VEND_CD VEND_CD
		, MV.VEND_ANAME VEND_ANAME
		, TA.ITEM_CD AS ITEM_CD
		, MI.ITEM_NAME
		, MP.MODEL
		, SUM(TA.ACPT_QTY) AS QTY
		, TA.ITEM_CD || TA.VEND_CD || NULL KEY_CD
		FROM
		  T_PAST_INSPC_ACPT TA
		, M_VEND_CTRL MV
		, M_PLANT_ITEM MP
		, M_ITEM MI
		WHERE 
		    TA.VEND_CD = MV.VEND_CD (+)
		AND TA.ITEM_CD = MI.ITEM_CD(+)
		AND TA.PLANT_CD = MP.PLANT_CD
		AND TA.ITEM_CD  = MP.ITEM_CD (+)
		AND TO_CHAR(TA.ACPT_DATE,'YYYY/MM/DD') >= TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,0),'MM'),'YYYY/MM/DD') AND TO_CHAR(TA.ACPT_DATE,'YYYY/MM/DD') <= TO_CHAR(LAST_DAY(ADD_MONTHS(SYSDATE,0)),'YYYY/MM/DD')
		GROUP BY
     	          MV.VEND_NAME 
    		, MV.VEND_ANAME
		, TA.VEND_CD 
		, TA.ITEM_CD 
		, MI.ITEM_NAME
		, MP.MODEL
		, TA.ITEM_CD || TA.VEND_CD || NULL