SELECT
 A.PLANT AS PLANT
,VM.PARENT_SEC_CD AS PD
,A.LINE_CD AS LINE_CD
,A.LINE_NAME AS LINE_NAME
,A.ITEM_CD AS ITEM_CD
,A.ITEM_NAME AS ITEM_NAME
,MP.MODEL
,NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') >= TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM'),'YYYY/MM/DD') AND  TO_CHAR(A.PDATE,'YYYY/MM/DD') <= TO_CHAR(LAST_DAY(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')),'YYYY/MM/DD')  THEN A.QTY END ),0)  AS PM 


,NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+0,'YYYY/MM/DD') THEN A.QTY END ),-1) AS P1  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+0,'YYYY/MM/DD') THEN A.QTY END ),-1) AS A1  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+0,'YYYY/MM/DD') THEN A.QTY END ),-1)         
-NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+0,'YYYY/MM/DD') THEN A.QTY END ),-1) AS D1  
,NVL(SUM(CASE WHEN A.STATUS = 3 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+0,'YYYY/MM/DD') THEN A.QTY END ),-1) AS N1  

,NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+1,'YYYY/MM/DD') THEN A.QTY END ),-1) AS P2  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+1,'YYYY/MM/DD') THEN A.QTY END ),-1) AS A2  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+1,'YYYY/MM/DD') THEN A.QTY END ),-1)         
-NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+1,'YYYY/MM/DD') THEN A.QTY END ),-1) AS D2  
,NVL(SUM(CASE WHEN A.STATUS = 3 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+1,'YYYY/MM/DD') THEN A.QTY END ),-1) AS N2  

,NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+2,'YYYY/MM/DD') THEN A.QTY END ),-1) AS P3  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+2,'YYYY/MM/DD') THEN A.QTY END ),-1) AS A3  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+2,'YYYY/MM/DD') THEN A.QTY END ),-1)         
-NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+2,'YYYY/MM/DD') THEN A.QTY END ),-1) AS D3  
,NVL(SUM(CASE WHEN A.STATUS = 3 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+2,'YYYY/MM/DD') THEN A.QTY END ),-1) AS N3  

,NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+3,'YYYY/MM/DD') THEN A.QTY END ),-1) AS P4  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+3,'YYYY/MM/DD') THEN A.QTY END ),-1) AS A4  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+3,'YYYY/MM/DD') THEN A.QTY END ),-1)         
-NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+3,'YYYY/MM/DD') THEN A.QTY END ),-1) AS D4  
,NVL(SUM(CASE WHEN A.STATUS = 3 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+3,'YYYY/MM/DD') THEN A.QTY END ),-1) AS N4  

,NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+4,'YYYY/MM/DD') THEN A.QTY END ),-1) AS P5  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+4,'YYYY/MM/DD') THEN A.QTY END ),-1) AS A5  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+4,'YYYY/MM/DD') THEN A.QTY END ),-1)         
-NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+4,'YYYY/MM/DD') THEN A.QTY END ),-1) AS D5  
,NVL(SUM(CASE WHEN A.STATUS = 3 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+4,'YYYY/MM/DD') THEN A.QTY END ),-1) AS N5  

,NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+5,'YYYY/MM/DD') THEN A.QTY END ),-1) AS P6  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+5,'YYYY/MM/DD') THEN A.QTY END ),-1) AS A6  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+5,'YYYY/MM/DD') THEN A.QTY END ),-1)         
-NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+5,'YYYY/MM/DD') THEN A.QTY END ),-1) AS D6  
,NVL(SUM(CASE WHEN A.STATUS = 3 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+5,'YYYY/MM/DD') THEN A.QTY END ),-1) AS N6  

,NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+6,'YYYY/MM/DD') THEN A.QTY END ),-1) AS P7  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+6,'YYYY/MM/DD') THEN A.QTY END ),-1) AS A7  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+6,'YYYY/MM/DD') THEN A.QTY END ),-1)         
-NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+6,'YYYY/MM/DD') THEN A.QTY END ),-1) AS D7  
,NVL(SUM(CASE WHEN A.STATUS = 3 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+6,'YYYY/MM/DD') THEN A.QTY END ),-1) AS N7  

,NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+7,'YYYY/MM/DD') THEN A.QTY END ),-1) AS P8  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+7,'YYYY/MM/DD') THEN A.QTY END ),-1) AS A8  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+7,'YYYY/MM/DD') THEN A.QTY END ),-1)         
-NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+7,'YYYY/MM/DD') THEN A.QTY END ),-1) AS D8  
,NVL(SUM(CASE WHEN A.STATUS = 3 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+7,'YYYY/MM/DD') THEN A.QTY END ),-1) AS N8  

,NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+8,'YYYY/MM/DD') THEN A.QTY END ),-1) AS P9  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+8,'YYYY/MM/DD') THEN A.QTY END ),-1) AS A9  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+8,'YYYY/MM/DD') THEN A.QTY END ),-1)         
-NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+8,'YYYY/MM/DD') THEN A.QTY END ),-1) AS D9  
,NVL(SUM(CASE WHEN A.STATUS = 3 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+8,'YYYY/MM/DD') THEN A.QTY END ),-1) AS N9  

,NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+9,'YYYY/MM/DD') THEN A.QTY END ),-1) AS P10  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+9,'YYYY/MM/DD') THEN A.QTY END ),-1) AS A10  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+9,'YYYY/MM/DD') THEN A.QTY END ),-1)         
-NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+9,'YYYY/MM/DD') THEN A.QTY END ),-1) AS D10  
,NVL(SUM(CASE WHEN A.STATUS = 3 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+9,'YYYY/MM/DD') THEN A.QTY END ),-1) AS N10  

,NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+10,'YYYY/MM/DD') THEN A.QTY END ),-1) AS P11  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+10,'YYYY/MM/DD') THEN A.QTY END ),-1) AS A11  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+10,'YYYY/MM/DD') THEN A.QTY END ),-1)         
-NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+10,'YYYY/MM/DD') THEN A.QTY END ),-1) AS D11  
,NVL(SUM(CASE WHEN A.STATUS = 3 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+10,'YYYY/MM/DD') THEN A.QTY END ),-1) AS N11  

,NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+11,'YYYY/MM/DD') THEN A.QTY END ),-1) AS P12  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+11,'YYYY/MM/DD') THEN A.QTY END ),-1) AS A12  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+11,'YYYY/MM/DD') THEN A.QTY END ),-1)         
-NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+11,'YYYY/MM/DD') THEN A.QTY END ),-1) AS D12  
,NVL(SUM(CASE WHEN A.STATUS = 3 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+11,'YYYY/MM/DD') THEN A.QTY END ),-1) AS N12  

,NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+12,'YYYY/MM/DD') THEN A.QTY END ),-1) AS P13  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+12,'YYYY/MM/DD') THEN A.QTY END ),-1) AS A13  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+12,'YYYY/MM/DD') THEN A.QTY END ),-1)         
-NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+12,'YYYY/MM/DD') THEN A.QTY END ),-1) AS D13  
,NVL(SUM(CASE WHEN A.STATUS = 3 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+12,'YYYY/MM/DD') THEN A.QTY END ),-1) AS N13  

,NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+13,'YYYY/MM/DD') THEN A.QTY END ),-1) AS P14  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+13,'YYYY/MM/DD') THEN A.QTY END ),-1) AS A14  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+13,'YYYY/MM/DD') THEN A.QTY END ),-1)         
-NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+13,'YYYY/MM/DD') THEN A.QTY END ),-1) AS D14  
,NVL(SUM(CASE WHEN A.STATUS = 3 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+13,'YYYY/MM/DD') THEN A.QTY END ),-1) AS N14  

,NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+14,'YYYY/MM/DD') THEN A.QTY END ),-1) AS P15  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+14,'YYYY/MM/DD') THEN A.QTY END ),-1) AS A15  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+14,'YYYY/MM/DD') THEN A.QTY END ),-1)         
-NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+14,'YYYY/MM/DD') THEN A.QTY END ),-1) AS D15  
,NVL(SUM(CASE WHEN A.STATUS = 3 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+14,'YYYY/MM/DD') THEN A.QTY END ),-1) AS N15  

,NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+15,'YYYY/MM/DD') THEN A.QTY END ),-1) AS P16  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+15,'YYYY/MM/DD') THEN A.QTY END ),-1) AS A16  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+15,'YYYY/MM/DD') THEN A.QTY END ),-1)         
-NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+15,'YYYY/MM/DD') THEN A.QTY END ),-1) AS D16  
,NVL(SUM(CASE WHEN A.STATUS = 3 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+15,'YYYY/MM/DD') THEN A.QTY END ),-1) AS N16  

,NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+16,'YYYY/MM/DD') THEN A.QTY END ),-1) AS P17  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+16,'YYYY/MM/DD') THEN A.QTY END ),-1) AS A17  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+16,'YYYY/MM/DD') THEN A.QTY END ),-1)         
-NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+16,'YYYY/MM/DD') THEN A.QTY END ),-1) AS D17  
,NVL(SUM(CASE WHEN A.STATUS = 3 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+16,'YYYY/MM/DD') THEN A.QTY END ),-1) AS N17  

,NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+17,'YYYY/MM/DD') THEN A.QTY END ),-1) AS P18  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+17,'YYYY/MM/DD') THEN A.QTY END ),-1) AS A18  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+17,'YYYY/MM/DD') THEN A.QTY END ),-1)         
-NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+17,'YYYY/MM/DD') THEN A.QTY END ),-1) AS D18  
,NVL(SUM(CASE WHEN A.STATUS = 3 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+17,'YYYY/MM/DD') THEN A.QTY END ),-1) AS N18  

,NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+18,'YYYY/MM/DD') THEN A.QTY END ),-1) AS P19  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+18,'YYYY/MM/DD') THEN A.QTY END ),-1) AS A19  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+18,'YYYY/MM/DD') THEN A.QTY END ),-1)         
-NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+18,'YYYY/MM/DD') THEN A.QTY END ),-1) AS D19  
,NVL(SUM(CASE WHEN A.STATUS = 3 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+18,'YYYY/MM/DD') THEN A.QTY END ),-1) AS N19  

,NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+19,'YYYY/MM/DD') THEN A.QTY END ),-1) AS P20  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+19,'YYYY/MM/DD') THEN A.QTY END ),-1) AS A20  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+19,'YYYY/MM/DD') THEN A.QTY END ),-1)         
-NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+19,'YYYY/MM/DD') THEN A.QTY END ),-1) AS D20  
,NVL(SUM(CASE WHEN A.STATUS = 3 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+19,'YYYY/MM/DD') THEN A.QTY END ),-1) AS N20  

,NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+20,'YYYY/MM/DD') THEN A.QTY END ),-1) AS P21  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+20,'YYYY/MM/DD') THEN A.QTY END ),-1) AS A21  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+20,'YYYY/MM/DD') THEN A.QTY END ),-1)         
-NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+20,'YYYY/MM/DD') THEN A.QTY END ),-1) AS D21  
,NVL(SUM(CASE WHEN A.STATUS = 3 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+20,'YYYY/MM/DD') THEN A.QTY END ),-1) AS N21  

,NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+21,'YYYY/MM/DD') THEN A.QTY END ),-1) AS P22  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+21,'YYYY/MM/DD') THEN A.QTY END ),-1) AS A22  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+21,'YYYY/MM/DD') THEN A.QTY END ),-1)         
-NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+21,'YYYY/MM/DD') THEN A.QTY END ),-1) AS D22  
,NVL(SUM(CASE WHEN A.STATUS = 3 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+21,'YYYY/MM/DD') THEN A.QTY END ),-1) AS N22  

,NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+22,'YYYY/MM/DD') THEN A.QTY END ),-1) AS P23  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+22,'YYYY/MM/DD') THEN A.QTY END ),-1) AS A23  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+22,'YYYY/MM/DD') THEN A.QTY END ),-1)         
-NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+22,'YYYY/MM/DD') THEN A.QTY END ),-1) AS D23  
,NVL(SUM(CASE WHEN A.STATUS = 3 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+22,'YYYY/MM/DD') THEN A.QTY END ),-1) AS N23  

,NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+23,'YYYY/MM/DD') THEN A.QTY END ),-1) AS P24  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+23,'YYYY/MM/DD') THEN A.QTY END ),-1) AS A24  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+23,'YYYY/MM/DD') THEN A.QTY END ),-1)         
-NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+23,'YYYY/MM/DD') THEN A.QTY END ),-1) AS D24  
,NVL(SUM(CASE WHEN A.STATUS = 3 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+23,'YYYY/MM/DD') THEN A.QTY END ),-1) AS N24  

,NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+24,'YYYY/MM/DD') THEN A.QTY END ),-1) AS P25  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+24,'YYYY/MM/DD') THEN A.QTY END ),-1) AS A25  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+24,'YYYY/MM/DD') THEN A.QTY END ),-1)         
-NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+24,'YYYY/MM/DD') THEN A.QTY END ),-1) AS D25  
,NVL(SUM(CASE WHEN A.STATUS = 3 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+24,'YYYY/MM/DD') THEN A.QTY END ),-1) AS N25  

,NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+25,'YYYY/MM/DD') THEN A.QTY END ),-1) AS P26  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+25,'YYYY/MM/DD') THEN A.QTY END ),-1) AS A26  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+25,'YYYY/MM/DD') THEN A.QTY END ),-1)         
-NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+25,'YYYY/MM/DD') THEN A.QTY END ),-1) AS D26  
,NVL(SUM(CASE WHEN A.STATUS = 3 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+25,'YYYY/MM/DD') THEN A.QTY END ),-1) AS N26  

,NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+26,'YYYY/MM/DD') THEN A.QTY END ),-1) AS P27  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+26,'YYYY/MM/DD') THEN A.QTY END ),-1) AS A27  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+26,'YYYY/MM/DD') THEN A.QTY END ),-1)         
-NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+26,'YYYY/MM/DD') THEN A.QTY END ),-1) AS D27  
,NVL(SUM(CASE WHEN A.STATUS = 3 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+26,'YYYY/MM/DD') THEN A.QTY END ),-1) AS N27  

,NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+27,'YYYY/MM/DD') THEN A.QTY END ),-1) AS P28  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+27,'YYYY/MM/DD') THEN A.QTY END ),-1) AS A28  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+27,'YYYY/MM/DD') THEN A.QTY END ),-1)         
-NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+27,'YYYY/MM/DD') THEN A.QTY END ),-1) AS D28  
,NVL(SUM(CASE WHEN A.STATUS = 3 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+27,'YYYY/MM/DD') THEN A.QTY END ),-1) AS N28  

,NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+28,'YYYY/MM/DD') THEN A.QTY END ),-1) AS P29  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+28,'YYYY/MM/DD') THEN A.QTY END ),-1) AS A29  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+28,'YYYY/MM/DD') THEN A.QTY END ),-1)         
-NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+28,'YYYY/MM/DD') THEN A.QTY END ),-1) AS D29  
,NVL(SUM(CASE WHEN A.STATUS = 3 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+28,'YYYY/MM/DD') THEN A.QTY END ),-1) AS N29  

,NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+29,'YYYY/MM/DD') THEN A.QTY END ),-1) AS P30  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+29,'YYYY/MM/DD') THEN A.QTY END ),-1) AS A30  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+29,'YYYY/MM/DD') THEN A.QTY END ),-1)         
-NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+29,'YYYY/MM/DD') THEN A.QTY END ),-1) AS D30  
,NVL(SUM(CASE WHEN A.STATUS = 3 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+29,'YYYY/MM/DD') THEN A.QTY END ),-1) AS N30  

,NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+30,'YYYY/MM/DD') THEN A.QTY END ),-1) AS P31  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+30,'YYYY/MM/DD') THEN A.QTY END ),-1) AS A31  
,NVL(SUM(CASE WHEN A.STATUS = 2 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+30,'YYYY/MM/DD') THEN A.QTY END ),-1)         
-NVL(SUM(CASE WHEN A.STATUS = 1 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+30,'YYYY/MM/DD') THEN A.QTY END ),-1) AS D31  
,NVL(SUM(CASE WHEN A.STATUS = 3 AND TO_CHAR(A.PDATE,'YYYY/MM/DD') = TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')+30,'YYYY/MM/DD') THEN A.QTY END ),-1) AS N31  


FROM
(SELECT
 1 AS STATUS
,TD.PLANT_CD AS PLANT
,TD.SOURCE_CD AS LINE_CD
,VD.SEC_NM AS LINE_NAME
,TD.ITEM_CD
,MI.ITEM_NAME 
--,MP.MODEL
,TD.ACPT_PLAN_DATE AS PDATE
,TD.ODR_QTY AS QTY
FROM
 (SELECT * FROM T_OD WHERE OD_TYP = 2 AND OUTSIDE_TYP = 1 AND NOT (ODR_STS_TYP = 9 AND TOTAL_RCV_QTY = 0)) TD
,VM_DEPARTMENT VD
,M_ITEM MI
--,M_PLANT_ITEM MP
WHERE 
    TD.ITEM_CD   = MI.ITEM_CD(+)
AND TD.SOURCE_CD = VD.SEC_CD(+)
AND TD.ODR_QTY > 0
AND NOT(TD.ODR_STS_TYP = 9 AND TD.TOTAL_RCV_QTY = 0)


UNION ALL

SELECT
 2 AS STATUS
,TR.PLANT_CD AS PLANT
,TR.WS_CD AS LINE_CD
,VD.SEC_NM AS LINE_NAME
,TR.ITEM_CD AS ITEM_CD
,MI.ITEM_NAME AS ITEM_NAME
,TR.OPR_DATE AS PDATE
,TR.ACPT_QTY AS QTY
FROM
 T_OPR_RSLT TR
,M_ITEM MI
,VM_DEPARTMENT VD
WHERE
TR.ITEM_CD = MI.ITEM_CD(+)
AND TR.WS_CD = VD.SEC_CD(+)

UNION ALL

SELECT
  3 AS STATUS
, TD.PLANT_CD AS PLANT
, TD.SOURCE_CD AS LINE_CD
, VM.SEC_NM AS LINE_NAME
, TD.ITEM_CD AS ITEM_CD
, MI.ITEM_NAME AS ITEM_NAME
, DF.RSLT_DATE AS PDATE
, DF.QTY AS QTY
FROM
  (SELECT PLANT_CD, SOURCE_CD,  ITEM_CD FROM T_OD WHERE OD_TYP = 2 AND OUTSIDE_TYP = 1 AND NOT (ODR_STS_TYP = 9 AND TOTAL_RCV_QTY = 0) GROUP BY PLANT_CD, SOURCE_CD,  ITEM_CD ) TD
, (SELECT ITEM_CD ,RSLT_DATE ,sum(QTY) QTY FROM UT_DEFECT_DISPOSAL  WHERE DEL_FLG = 0  AND TO_CHAR(RSLT_DATE,'YYYY/MM/DD') >= TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM'),'YYYY/MM/DD') AND TO_CHAR(RSLT_DATE,'YYYY/MM/DD') <= TO_CHAR(LAST_DAY(TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')),'YYYY/MM/DD') GROUP BY ITEM_CD, RSLT_DATE) DF
, VM_DEPARTMENT_CLASS VC
, VM_DEPARTMENT VM
, M_PLANT_ITEM MP
, M_ITEM MI
WHERE
    TD.SOURCE_CD = VC.COMP_SEC_CD(+)
AND TD.ITEM_CD = MI.ITEM_CD(+)
AND TD.ITEM_CD = MP.ITEM_CD(+)
AND TD.SOURCE_CD = VM.SEC_CD(+)
AND TD.ITEM_CD = DF.ITEM_CD(+)
--AND TD.SOURCE_CD = DF.WS_CD(+)
AND DF.QTY IS NOT NULL
AND MP.MODEL  IS NOT NULL

) A
,VM_DEPARTMENT_CLASS VM
,VM_DEPARTMENT VDD
,M_PLANT_ITEM MP
WHERE
A.LINE_CD = VM.COMP_SEC_CD(+)
AND A.LINE_CD = VDD.SEC_CD(+)
AND A.ITEM_CD = MP.ITEM_CD(+)
AND VM.PARENT_SEC_CD IS NOT NULL
AND A.LINE_CD   IS NOT NULL
AND A.ITEM_NAME IS NOT NULL
AND NOT ( A.LINE_CD IN ('K1PC99') )
AND A.LINE_NAME IS NOT NULL
--AND MP.MODEL IS NOT NULL
--AND VM.PARENT_SEC_CD = 'K1PL00'


GROUP BY
 A.PLANT
,VM.PARENT_SEC_CD
,A.LINE_CD
,A.LINE_NAME
,A.ITEM_CD
,A.ITEM_NAME
,MP.MODEL
ORDER BY
 A.PLANT
,VM.PARENT_SEC_CD
,A.LINE_CD
,MP.MODEL