SELECT 
  MT.CUST_GRP_CD
, TS.ITEM_CD
, MI.ITEM_NAME
, MP.MODEL
, TS.SHIP_UNIT_PRICE PRICE
, SUM(TS.SHIP_QTY) AS "Q'TY" 
, SUM(TS.SHIP_AMOUNT) AMOUNT
, TO_CHAR(SYSDATE - 0.082, 'YYYY/MM/DD HH24:MI:SS') UPDATE_DATE
---, TO_CHAR(TS.DESINATED_DLV_DATE, 'YYYY/MM/DD') DLV
FROM 
 T_SHIP TS
,M_CUST MT
,M_ITEM MI
,M_PLANT_ITEM MP
WHERE 
      TS.CUST_CD = MT.CUST_CD(+)
 --     TS.CUST_CD = MC.CUST_CD(+)
 AND  TS.ITEM_CD = MI.ITEM_CD(+)
 AND  TS.ITEM_CD = MP.ITEM_CD(+)
--AND	(MT.CUST_ANAME LIKE '%MEC%') 
 AND MT.CUST_GRP_CD IN( 'D20200', 'D20100', 'D20300', 'F30400', 'D20700') 
 AND NOT (MP.MODEL LIKE '%VD00%' OR MP.MODEL LIKE '%700P%')
--AND TS.ITEM_CD = 'MD181579'
--AND MP.MODEL LIKE '%4P%'
AND  ( TO_CHAR(TS.DESINATED_DLV_DATE,'YYYY/MM/DD') BETWEEN '2019/05/01' AND '2019/05/31' )

GROUP BY 
   TS.ITEM_CD
 , MP.MODEL
 , MI.ITEM_NAME
 , TS.SHIP_UNIT_PRICE
 , MT.CUST_GRP_CD

ORDER BY 1  , 4